/* Ciclone host shim for src/config.h - shadows the real config.h via -I order.
 *
 * The real config.h does `#include "autoconf.h"` (generated by conf2h.awk from
 * config-mk3) then `#include CONFIG_MCU_H` (the LPC17xx CMSIS header). On the
 * host we replace BOTH: this file defines the handful of config-mk3 constants
 * the portable firmware actually uses, points CONFIG_MCU_H at host_lpc.h, and
 * turns every GPIO/bit-band macro into a no-op EXCEPT the FPGA chip-select,
 * which is routed to the SPI seam (ciclone_spi_select/deselect).
 *
 * Result: the real firmware C (main.c, snes.c, memory.c, fpga_spi.c, ...)
 * compiles unmodified and its FPGA SPI traffic flows to the FpgaModel.
 */
#ifndef CICLONE_HOST_CONFIG_H
#define CICLONE_HOST_CONFIG_H

/* Also claim the REAL src/config.h include guard: headers that live in src/
 * (fpga.h, snes.h, ...) do `#include "config.h"` and their quoted include
 * resolves to src/config.h FIRST (includer-directory rule). Defining its guard
 * here makes that real header expand to nothing, so our shadow wins everywhere. */
#ifndef _CONFIG_H
#define _CONFIG_H
#endif

/* System headers FIRST, before __attribute__ is neutralised, so the macro never
 * rewrites their own attribute uses. */
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Keep __attribute__ FUNCTIONAL on the host: the firmware's packed structs carry
 * _Static_assert offset checks (cfg.c) that only pass when packing is real, and
 * clang supports packed/aligned/used natively. The only attribute clang rejects
 * on Mach-O is a bare section name ("requires segment,section"). Neutralise just
 * that by making `section(x)` an empty function-like macro: the firmware's
 * __attribute__((section(".ahbram"))) / ((used, section(".fwhdr"))) collapse to
 * a harmless empty/used attribute, while packed/aligned keep working. (`section`
 * appears in the sources only inside these attributes - verified.) */
#define section(x)

/* ---- config-mk3 derived constants (mirror src/config-mk3) ---------------- */
#define CONFIG_MK3              1
#define CONFIG_ARCH            lpc175x
#define CONFIG_MCU_FOSC        8000000
#define F_OSC                  8000000UL
#define CONFIG_CPU_FREQUENCY   96000000
#define DEVICE_NAME            "sd2snes Mk.III (ciclone host)"
#define MENU_FILENAME          "/sd2snes/m3nu.bin"
#define ONBOARDING_FILENAME    "/sd2snes/onboarding.bin"
#define FPGA_CONF_EXT          "bi3"

#define CONFIG_FW_START        0xc000
#define CONFIG_FW_HEADERSIZE   0x100

#define CONFIG_UART_NUM            3
#define CONFIG_UART_TX_BUF_SHIFT   8
#define CONFIG_UART_BAUDRATE       921600

#define QSORT_MAXELEM   2048
#define SORT_STRLEN     256
#define CLTBL_SIZE      100
#define DIR_FILE_MAX    16380

/* RAM connection test (src/memtest.c) -- mirror of config-mk3 */
#define RAM0_NUM_CHIPS      (2)
#define RAM0_BASES          {0, 2}
#define RAM0_SECOND_ADDR    (4)
#define MEMTEST_ITERATIONS  (256)
#define CONFIG_UART_DEBUG   1

/* Point the firmware's `#include CONFIG_MCU_H` at our host stand-in. */
#define CONFIG_MCU_H   "host_lpc.h"
#include "host_lpc.h"

/* BITBAND / BV live in the host bits.h shadow (every pin reads as 1; see there).
 * Pulled in here so config.h-only includers still have them. */
#include "bits.h"

/* Pin the FatFs integer types to fixed widths (host `long` is 64-bit; FatFs
 * needs DWORD==32-bit). Force-included config.h pulls our shadow integer.h
 * FIRST so its _INTEGER guard neutralises the real src/integer.h. */
#include "integer.h"

/* ---- GPIO register tokens (mirror config-mk3 pin map) -------------------- *
 * Only the (reg,bit) identity matters on the host. FPGA_SSREG/SSBIT must be a
 * pair distinct from every other (reg,bit) used with SET_BIT/CLEAR_BIT so the
 * seam triggers on exactly the FPGA chip-select. (LPC_GPIO0 bit 16.) */
#define SNES_RESET_REG       LPC_GPIO1
#define SNES_RESET_BIT       4
#define SNES_CIC_PAIR_REG    LPC_GPIO1
#define SNES_CIC_PAIR_BIT    14
#define SNES_CIC_D0_REG      LPC_GPIO1
#define SNES_CIC_D0_BIT      8
#define SNES_CIC_D1_REG      LPC_GPIO1
#define SNES_CIC_D1_BIT      9
#define SNES_CIC_STATUS_REG  LPC_GPIO1
#define SNES_CIC_STATUS_BIT  10

#define FPGA_SSREG           LPC_GPIO0
#define FPGA_SSBIT           16
#define FPGA_MCU_RDY_REG     LPC_GPIO2
#define FPGA_MCU_RDY_BIT     8

#define SPI_REGS             LPC_SSP0
#define SPI_SR               SR
#define SPI_SSELREG          LPC_GPIO0
#define SPI_SSELBIT          16

#define GPIO_I  FIOPIN
#define GPIO_O  FIOPIN

/* ---- FPGA chip-select seam --------------------------------------------- *
 * SET_BIT raises a pin, CLEAR_BIT lowers it. The FPGA SS is active-low:
 *   FPGA_SELECT()   = ...; CLEAR_BIT(FPGA_SSREG, FPGA_SSBIT)  -> assert  -> select
 *   FPGA_DESELECT() = ...; SET_BIT(FPGA_SSREG, FPGA_SSBIT)    -> release -> deselect
 * Only that exact (reg,bit) drives the seam; every other GPIO write is a no-op. */
#ifdef __cplusplus
extern "C" {
#endif
void ciclone_spi_select(void);
void ciclone_spi_deselect(void);
#ifdef __cplusplus
}
#endif

static inline void ciclone_gpio_set(void *reg, int bit) {
  if (reg == (void *)FPGA_SSREG && bit == FPGA_SSBIT) ciclone_spi_deselect();
}
static inline void ciclone_gpio_clr(void *reg, int bit) {
  if (reg == (void *)FPGA_SSREG && bit == FPGA_SSBIT) ciclone_spi_select();
}

#define SET_BIT(reg, b)        ciclone_gpio_set((void *)(reg), (b))
#define CLEAR_BIT(reg, b)      ciclone_gpio_clr((void *)(reg), (b))
#define OUT_BIT(reg, b, val)   do { if (val) SET_BIT(reg, b); else CLEAR_BIT(reg, b); } while (0)

/* ---- GPIO config macros -> no-ops on the host --------------------------- */
#define GPIO_DIR(reg, b, dir)     do {} while (0)
#define GPIO_MODE_OUT(reg, b)     do {} while (0)
#define GPIO_MODE_IN(reg, b)      do {} while (0)
#define GPIO_MODE_AF(reg, b, af)  do {} while (0)
#define GPIO_MODE_ANALOG(reg, b)  do {} while (0)
#define GPIO_OPENDRAIN(reg, b)    do {} while (0)
#define GPIO_PUSHPULL(reg, b)     do {} while (0)
#define GPIO_PULLUP(reg, b)       do {} while (0)
#define GPIO_PULLDOWN(reg, b)     do {} while (0)
#define GPIO_PULLNONE(reg, b)     do {} while (0)
#define GPIO_SPEED(reg, b, sp)    do {} while (0)

/* FPGA serial-configuration bit-bang macros -> no-ops (the real fpga.c that
 * uses these is replaced by hal_host/fpga_host.c; defined here too so any stray
 * include compiles). */
#define SET_FPGA_DIN(data)            do {} while (0)
#define FPGA_DIN_MASK()               do {} while (0)
#define FPGA_DIN_UNMASK()             do {} while (0)
#define FPGA_SEND_BYTE_SERIAL(data)   do {} while (0)
#define SD_DAT_MASK()                 do {} while (0)
#define SD_DAT_UNMASK()               do {} while (0)

/* ---- misc from the real config.h ---------------------------------------- */
#define IN_AHBRAM
#define SDCARD_DETECT       (1)     /* card always "present" on the host */
#define SDCARD_WP           (0)
#define SD_SUPPLY_VOLTAGE   (1L << 21)
#define CONFIG_SD_BLOCKTRANSFER   1
#define CONFIG_SD_AUTO_RETRIES    10
#define CONFIG_FWVER        (0)

#endif /* CICLONE_HOST_CONFIG_H */
